### ISSUE TITLE
code girls 

### ISSUE THREAD

**Issue by orchid00** [orchid00/WomenAreExcellentProgrammers#1]
Just read this interview about the writing of code girls. I was just great! I don't know how It has been invisible to me all these years https://edition.cnn.com/2017/10/11/opinions/code-girls-iiza-mundy-opinion/index.html I am looking forward to read more and watch the movie. I must add this to the list.

**Comment by amandamiotto** [comment]
This is awesome! I had no idea!


Amanda Miotto | Senior eResearch Analyst


eResearch Services - Digital Solutions

Griffith University/ QCIF | Nathan | QLD 4111

T +61 7 373 54697 | @amandamiottoGU |

 a.miotto@griffith.edu.au

Hacky Hour: Griffith.edu.au/hackyhour | @hackyhourGU



Griffith University - CRICOS Provider Number 00233E


PRIVILEGED - PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the use of the addressee(s) and may contain information which is confidential or privileged. If you receive this email and you are not the addressee or responsible for delivery of the email to the addressee(s), please disregard the contents of the email, delete the mail and notify the author immediately.


________________________________
